# Импорт библиотек

In [38]:
import pandas as pd
import numpy as np
from ydata_profiling import ProfileReport
import matplotlib.pyplot as plt

In [35]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 20)

# Предпросмотр и начальная обработка

In [26]:
df = pd.read_csv("datasets/dataset_1.csv")

In [30]:
df.head(5)

,id,time,processing_time,lon,lat,height,depth,course,angle,num_sattelites,moving_type,rotation,rod_change,pressure_air,pressure_axis,pressure_rotation,electric_rotation,electric_pressure_axis,voltage_rotation,voltage_pressure_axis,time_stamp,sequence_id,block_well_id,rig_id,well_id,drilling_speed,rtk_status,d_depth,d_time,speed,n/p,EI,EI 0-1,EI 1-2,EI 2-3,EI 3-4,EI 4-5,EI 5-6,EI 6-7
0,23061521,2025-10-07 22:18:02,2025-10-07 22:18:09.425,60.921372,53.208426,205.072378,4.5753,208,92.2,37,1,107.010,0.0,502,9610,9741,NaN,NaN,NaN,NaN,NaN,6,NaN,49,25512,NaN,True,0.4545,NaN,NaN,0.011135,6.580100e+04,7826.0000,14913.00000,17481.0,9998.0,5353.0,4888.0,2660.0
1,23061529,2025-10-07 22:18:08,2025-10-07 22:18:14.495,60.921372,53.208426,205.061214,4.6965,256,93.4,37,1,104.892,0.0,497,12781,13144,NaN,NaN,NaN,NaN,NaN,6,NaN,49,25512,NaN,True,0.1212,6.0,0.02020,0.008207,8.723352e+11,0.0202,0.00000,0.0,0.0,0.0,0.0,0.0
2,23061535,2025-10-07 22:18:13,2025-10-07 22:18:19.239,60.921372,53.208427,205.078345,4.8783,359,93.0,37,1,101.430,0.0,501,18971,18936,NaN,NaN,NaN,NaN,NaN,6,NaN,49,25512,NaN,True,0.1818,5.0,0.03636,0.005347,1.002123e+12,0.0000,0.03636,0.0,0.0,0.0,0.0,0.0
3,23061542,2025-10-07 22:18:18,2025-10-07 22:18:24.208,60.921373,53.208425,205.054763,5.0298,170,92.1,37,1,101.430,0.0,544,20153,18184,NaN,NaN,NaN,NaN,NaN,6,NaN,49,25512,NaN,True,0.1515,5.0,0.03030,0.005033,1.226741e+12,0.0000,0.03030,0.0,0.0,0.0,0.0,0.0
4,23061551,2025-10-07 22:18:23,2025-10-07 22:18:29.385,60.921372,53.208425,205.065585,5.1813,218,93.0,37,1,102.714,0.0,559,20162,17445,NaN,NaN,NaN,NaN,NaN,6,NaN,49,25512,NaN,True,0.1515,5.0,0.03030,0.005094,1.192317e+12,0.0000,0.03030,0.0,0.0,0.0,0.0,0.0

In [ ]:
plt.

In [36]:
df[['rotation', 'pressure_rotation']].sample(20)

        rotation  pressure_rotation
22645    104.742              13093
2222      99.600              19750
4286     103.902              13823
103179   138.702              17077
46787    138.906              16147
110980   138.660              16456
142533   103.110              19306
62042    104.346              11504
135937   103.602              16994
87792    106.122              11200
114847   138.414              14448
128576   138.324              12402
13728    104.298              16200
73816    138.414              12449
17375    103.458              16047
129855   106.080              13321
47879    138.996              11371
11180    102.270              20399
26898    104.640              13835
9721     111.270               7571

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 165966 entries, 0 to 165965
Data columns (total 39 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   id                      165966 non-null  int64
 1   time                    165966 non-null  object
 2   processing_time         165966 non-null  object
 3   lon                     165966 non-null  float64
 4   lat                     165966 non-null  float64
 5   height                  165966 non-null  float64
 6   depth                   165966 non-null  float64
 7   course                  165966 non-null  int64
 8   angle                   165966 non-null  float64
 9   num_sattelites          165966 non-null  int64
 10  moving_type             165966 non-null  int64
 11  rotation                165966 non-null  float64
 12  rod_change              165966 non-null  float64
 13  pressure_air            165966 non-null  int64
 14  pressure_axis           165966 non-null  int64
 15  pressure_rotation       165966 non-null  int64
 16  electric_rotation       0 non-null       float64
 17  electric_pressure_axis  0 non-null       float64
 18  voltage_rotation        0 non-null       float64
 19  voltage_pressure_axis   0 non-null       float64
 20  time_stamp              0 non-null       float64
 21  sequence_id             165966 non-null  int64
 22  block_well_id           21970 non-null   float64
 23  rig_id                  165966 non-null  int64
 24  well_id                 165966 non-null  int64
 25  drilling_speed          0 non-null       float64
 26  rtk_status              165966 non-null  bool
 27  d_depth                 165966 non-null  float64
 28  d_time                  165552 non-null  float64
 29  speed                   165552 non-null  float64
 30  n/p                     165966 non-null  float64
 31  EI                      165553 non-null  float64
 32  EI 0-1                  165966 non-null  float64
 33  EI 1-2                  165966 non-null  float64
 34  EI 2-3                  165966 non-null  float64
 35  EI 3-4                  165966 non-null  float64
 36  EI 4-5                  165966 non-null  float64
 37  EI 5-6                  165966 non-null  float64
 38  EI 6-7                  165966 non-null  float64
dtypes: bool(1), float64(26), int64(10), object(2)
memory usage: 48.3+ MB

### Удаление пустых колонок

In [ ]:
df = df.drop(columns=[
    'electric_rotation',
    'electric_pressure_axis',
    'voltage_rotation',
    'voltage_pressure_axis',
    'time_stamp',
    'drilling_speed'
])

In [32]:
df.corr()

ValueError: could not convert string to float: '2025-10-07 22:18:02'

### конвертация времени

In [14]:
df['time'] = pd.to_datetime(df['time'], errors='coerce')
df['processing_time'] = pd.to_datetime(df['processing_time'], errors='coerce')

In [17]:
df.head(5)

,id,time,processing_time,lon,lat,height,depth,course,angle,num_sattelites,moving_type,rotation,rod_change,pressure_air,pressure_axis,pressure_rotation,sequence_id,block_well_id,rig_id,well_id,rtk_status,d_depth,d_time,speed,n/p,EI,EI 0-1,EI 1-2,EI 2-3,EI 3-4,EI 4-5,EI 5-6,EI 6-7
0,23061521,2025-10-07 22:18:02,2025-10-07 22:18:09.425,60.921372,53.208426,205.072378,4.5753,208,92.2,37,1,107.010,0.0,502,9610,9741,6,NaN,49,25512,True,0.4545,NaN,NaN,0.011135,6.580100e+04,7826.0000,14913.00000,17481.0,9998.0,5353.0,4888.0,2660.0
1,23061529,2025-10-07 22:18:08,2025-10-07 22:18:14.495,60.921372,53.208426,205.061214,4.6965,256,93.4,37,1,104.892,0.0,497,12781,13144,6,NaN,49,25512,True,0.1212,6.0,0.02020,0.008207,8.723352e+11,0.0202,0.00000,0.0,0.0,0.0,0.0,0.0
2,23061535,2025-10-07 22:18:13,2025-10-07 22:18:19.239,60.921372,53.208427,205.078345,4.8783,359,93.0,37,1,101.430,0.0,501,18971,18936,6,NaN,49,25512,True,0.1818,5.0,0.03636,0.005347,1.002123e+12,0.0000,0.03636,0.0,0.0,0.0,0.0,0.0
3,23061542,2025-10-07 22:18:18,2025-10-07 22:18:24.208,60.921373,53.208425,205.054763,5.0298,170,92.1,37,1,101.430,0.0,544,20153,18184,6,NaN,49,25512,True,0.1515,5.0,0.03030,0.005033,1.226741e+12,0.0000,0.03030,0.0,0.0,0.0,0.0,0.0
4,23061551,2025-10-07 22:18:23,2025-10-07 22:18:29.385,60.921372,53.208425,205.065585,5.1813,218,93.0,37,1,102.714,0.0,559,20162,17445,6,NaN,49,25512,True,0.1515,5.0,0.03030,0.005094,1.192317e+12,0.0000,0.03030,0.0,0.0,0.0,0.0,0.0

### профайлер

In [16]:

profile = ProfileReport(
    df,
    title="Drilling Data Profiling",
    explorative=True
)

profile.to_file("drilling_profile.html")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

100%|██████████| 33/33 [00:02<00:00, 12.38it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]