In [5]:
import pandas as pd

In [6]:
df = pd.read_csv("cleared.csv", index_col=0)

In [7]:
df2 = pd.read_csv("../datasets/dataset_2.csv")
df2.columns

Index(['id', 'time', 'processing_time', 'lon', 'lat', 'height', 'depth',
       'course', 'angle', 'num_sattelites', 'moving_type', 'rotation',
       'rod_change', 'pressure_air', 'pressure_axis', 'pressure_rotation',
       'electric_rotation', 'electric_pressure_axis', 'voltage_rotation',
       'voltage_pressure_axis', 'time_stamp', 'sequence_id', 'block_well_id',
       'rig_id', 'well_id', 'drilling_speed', 'rtk_status', 'd_depth',
       'd_time', 'speed', 'n/p', 'EI', 'EI 0-1', 'EI 1-2', 'EI 2-4', 'EI 4-6',
       'EI 6-8', 'EI 8-10', 'EI 10-12'],
      dtype='str')

In [ ]:
df2 = df2[df.columns]

Index(['time', 'processing_time', 'depth', 'course', 'rotation',
       'pressure_air', 'pressure_axis', 'pressure_rotation', 'well_id',
       'd_depth', 'd_time', 'speed', 'n/p', 'EI'],
      dtype='str')

In [ ]:
df2.drop(columns=['course', 'pressure_air', 'n/p', 'processing_time']

In [ ]:
, inplace=True)

In [50]:
df2

,time,depth,rotation,pressure_axis,pressure_rotation,well_id,d_depth,d_time,speed,EI
0,2025-08-12 19:00:57,0.7000,38.650,1040,5672,18347,0.7000,NaN,NaN,2.716740e+05
1,2025-08-13 18:25:33,0.3000,25.900,1133,6457,18437,0.3000,NaN,NaN,NaN
2,2025-08-13 22:34:06,0.4000,16.750,901,3887,18451,0.4000,NaN,NaN,NaN
3,2025-08-13 22:45:25,0.5000,12.300,3403,3647,18456,0.5000,NaN,NaN,NaN
4,2025-08-15 04:11:43,1.0000,3.100,1114,5751,18597,1.0000,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
272956,2025-10-07 22:14:47,3.7572,104.598,10071,13434,25512,3.7572,5.0,0.75144,1.883246e+10
272957,2025-10-07 22:14:52,3.9390,105.978,12308,12992,25512,3.9390,5.0,0.78780,2.151113e+10
272958,2025-10-07 22:14:58,4.0299,105.978,12363,15220,25512,4.0299,6.0,0.67165,2.969007e+10
272959,2025-10-07 22:15:03,4.0905,102.420,13499,14416,25512,4.0905,5.0,0.81810,2.436266e+10
272960,2025-10-07 22:15:08,4.1208,103.944,14851,15670,25512,4.1208,5.0,0.82416,2.935030e+10

In [51]:
df2.to_csv("cleared2.csv")

In [38]:
df[df['well_id']==25512]

,time,processing_time,depth,course,rotation,pressure_air,pressure_axis,pressure_rotation,well_id,d_depth,d_time,speed,n/p,EI
0,2025-10-07 22:18:02,2025-10-07 22:18:09.425,4.5753,208,107.010,502,9610,9741,25512,0.4545,NaN,NaN,0.011135,6.580100e+04
1,2025-10-07 22:18:08,2025-10-07 22:18:14.495,4.6965,256,104.892,497,12781,13144,25512,0.1212,6.0,0.02020,0.008207,8.723352e+11
2,2025-10-07 22:18:13,2025-10-07 22:18:19.239,4.8783,359,101.430,501,18971,18936,25512,0.1818,5.0,0.03636,0.005347,1.002123e+12
3,2025-10-07 22:18:18,2025-10-07 22:18:24.208,5.0298,170,101.430,544,20153,18184,25512,0.1515,5.0,0.03030,0.005033,1.226741e+12
4,2025-10-07 22:18:23,2025-10-07 22:18:29.385,5.1813,218,102.714,559,20162,17445,25512,0.1515,5.0,0.03030,0.005094,1.192317e+12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
270,2025-10-07 22:47:10,2025-10-07 22:47:17.784,27.8154,267,104.154,618,19779,15876,25512,0.0606,5.0,0.01212,0.005266,2.698477e+12
271,2025-10-07 22:47:15,2025-10-07 22:47:23.182,27.9063,224,103.458,618,19785,16385,25512,0.0909,5.0,0.01818,0.005229,1.844814e+12
272,2025-10-07 22:47:20,2025-10-07 22:47:27.929,27.9972,127,101.676,618,19770,18126,25512,0.0909,5.0,0.01818,0.005143,2.004164e+12
273,2025-10-07 22:47:25,2025-10-07 22:47:32.654,28.0578,160,102.372,619,19787,16928,25512,0.0606,5.0,0.01212,0.005174,2.829203e+12
274,2025-10-07 22:47:31,2025-10-07 22:47:38.208,28.1184,335,104.790,622,19230,14983,25512,0.0606,6.0,0.01010,0.005449,2.989348e+12

In [39]:
df2[df2['well_id']==25512]

,time,processing_time,depth,course,rotation,pressure_air,pressure_axis,pressure_rotation,well_id,d_depth,d_time,speed,n/p,EI
272931,2025-10-07 22:12:30,2025-10-07 22:12:37.672,0.0303,163,73.140,287,3201,6449,25512,0.0303,NaN,NaN,0.022849,NaN
272932,2025-10-07 22:12:35,2025-10-07 22:12:38.128,0.1515,6,90.558,296,3214,6807,25512,0.1515,5.0,0.030300,0.028176,6.538616e+10
272933,2025-10-07 22:12:40,2025-10-07 22:12:48.521,0.3030,184,81.666,293,3231,7626,25512,0.3030,5.0,0.060600,0.025276,3.320492e+10
272934,2025-10-07 22:12:45,2025-10-07 22:12:53.262,0.4242,228,85.158,288,3188,6815,25512,0.4242,5.0,0.084840,0.026712,2.180765e+10
272935,2025-10-07 22:12:51,2025-10-07 22:12:58.189,0.5454,57,83.742,285,4182,8401,25512,0.5454,6.0,0.090900,0.020024,3.236640e+10
272936,2025-10-07 22:12:56,2025-10-07 22:13:03.732,0.7272,354,85.158,286,4323,7807,25512,0.7272,5.0,0.145440,0.019699,1.976109e+10
272937,2025-10-07 22:13:01,2025-10-07 22:13:09.024,0.8484,3,84.864,288,4459,8248,25512,0.8484,5.0,0.169680,0.019032,1.839412e+10
272938,2025-10-07 22:13:06,2025-10-07 22:13:13.405,0.9696,88,107.460,287,4444,10244,25512,0.9696,5.0,0.193920,0.024181,2.522713e+10
272939,2025-10-07 22:13:12,2025-10-07 22:13:19.074,1.1211,199,108.006,290,4524,9287,25512,1.1211,6.0,0.186850,0.023874,2.428582e+10
272940,2025-10-07 22:13:17,2025-10-07 22:13:23.769,1.2120,319,108.048,290,4524,9434,25512,1.2120,5.0,0.242400,0.023883,1.902403e+10
272941,2025-10-07 22:13:22,2025-10-07 22:13:29.407,1.3332,22,107.754,299,5634,9318,25512,1.3332,5.0,0.266640,0.019126,2.121523e+10
272942,2025-10-07 22:13:28,2025-10-07 22:13:34.014,1.5453,323,107.010,293,5860,10910,25512,1.5453,6.0,0.257550,0.018261,2.656349e+10
272943,2025-10-07 22:13:33,2025-10-07 22:13:39.654,1.7271,29,107.268,290,5914,10210,25512,1.7271,5.0,0.345420,0.018138,1.875123e+10
272944,2025-10-07 22:13:39,2025-10-07 22:13:44.145,1.8786,159,106.122,287,7235,11647,25512,1.8786,6.0,0.313100,0.014668,2.856110e+10
272945,2025-10-07 22:13:44,2025-10-07 22:13:53.611,1.9695,359,107.010,289,7962,10282,25512,1.9695,5.0,0.393900,0.013440,2.224017e+10
272946,2025-10-07 22:13:49,2025-10-07 22:13:54.055,2.0301,34,106.674,291,7964,12227,25512,2.0301,5.0,0.406020,0.013395,2.558364e+10
272947,2025-10-07 22:13:54,2025-10-07 22:13:58.654,2.1210,200,104.940,358,8286,12127,25512,2.1210,5.0,0.424200,0.012665,2.485814e+10
272948,2025-10-07 22:14:00,2025-10-07 22:14:09.752,2.1816,40,104.640,469,8288,14181,25512,2.1816,6.0,0.363600,0.012625,3.382443e+10
272949,2025-10-07 22:14:05,2025-10-07 22:14:10.215,2.2725,300,105.678,520,9224,13524,25512,2.2725,5.0,0.454500,0.011457,2.900515e+10
272950,2025-10-07 22:14:10,2025-10-07 22:14:14.268,2.3634,147,105.234,531,9217,12719,25512,2.3634,5.0,0.472680,0.011417,2.609945e+10
272951,2025-10-07 22:14:15,2025-10-07 22:14:19.794,2.4240,59,105.384,537,9216,13740,25512,2.4240,5.0,0.484800,0.011435,2.752588e+10
272952,2025-10-07 22:14:21,2025-10-07 22:14:30.188,2.5452,220,102.522,542,9994,11517,25512,2.5452,6.0,0.424200,0.010258,2.781795e+10
272953,2025-10-07 22:14:26,2025-10-07 22:14:34.686,2.7876,206,105.978,533,10007,11881,25512,2.7876,5.0,0.557520,0.010590,2.260019e+10
272954,2025-10-07 22:14:31,2025-10-07 22:14:39.158,3.0603,346,106.566,530,9950,14950,25512,3.0603,5.0,0.612060,0.010710,2.589935e+10
272955,2025-10-07 22:14:42,2025-10-07 22:14:49.501,3.5754,187,104.496,530,10096,13221,25512,3.5754,11.0,0.325036,0.010350,4.291226e+10
272956,2025-10-07 22:14:47,2025-10-07 22:14:55.384,3.7572,317,104.598,530,10071,13434,25512,3.7572,5.0,0.751440,0.010386,1.883246e+10
272957,2025-10-07 22:14:52,2025-10-07 22:14:59.667,3.9390,128,105.978,540,12308,12992,25512,3.9390,5.0,0.787800,0.008610,2.151113e+10
272958,2025-10-07 22:14:58,2025-10-07 22:15:05.094,4.0299,352,105.978,536,12363,15220,25512,4.0299,6.0,0.671650,0.008572,2.969007e+10
272959,2025-10-07 22:15:03,2025-10-07 22:15:10.387,4.0905,1,102.420,575,13499,14416,25512,4.0905,5.0,0.818100,0.007587,2.436266e+10
272960,2025-10-07 22:15:08,2025-10-07 22:15:14.657,4.1208,109,103.944,607,14851,15670,25512,4.1208,5.0,0.824160,0.006999,2.935030e+10

In [36]:
set(df2['well_id']) & set(df['well_id'])

{25512}