# Импорт библиотек

In [ ]:
import sys
from pathlib import Path
sys.path.append(str(Path().resolve().parent))

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from config import DATASETS_DIR

In [63]:
df = pd.read_csv("datasets/dataset_1.csv")
df.head(3)

,id,time,processing_time,lon,lat,height,depth,course,angle,num_sattelites,...,speed,n/p,EI,EI 0-1,EI 1-2,EI 2-3,EI 3-4,EI 4-5,EI 5-6,EI 6-7
0,23061521,2025-10-07 22:18:02,2025-10-07 22:18:09.425,60.921372,53.208426,205.072378,4.5753,208,92.2,37,...,NaN,0.011135,6.580100e+04,7826.0000,14913.00000,17481.0,9998.0,5353.0,4888.0,2660.0
1,23061529,2025-10-07 22:18:08,2025-10-07 22:18:14.495,60.921372,53.208426,205.061214,4.6965,256,93.4,37,...,0.02020,0.008207,8.723352e+11,0.0202,0.00000,0.0,0.0,0.0,0.0,0.0
2,23061535,2025-10-07 22:18:13,2025-10-07 22:18:19.239,60.921372,53.208427,205.078345,4.8783,359,93.0,37,...,0.03636,0.005347,1.002123e+12,0.0000,0.03636,0.0,0.0,0.0,0.0,0.0

In [64]:
df['rod_change'].value_counts()

rod_change
0.00    165931
0.05        23
1.00        12
Name: count, dtype: int64

In [65]:
df.columns

Index(['id', 'time', 'processing_time', 'lon', 'lat', 'height', 'depth',
       'course', 'angle', 'num_sattelites', 'moving_type', 'rotation',
       'rod_change', 'pressure_air', 'pressure_axis', 'pressure_rotation',
       'electric_rotation', 'electric_pressure_axis', 'voltage_rotation',
       'voltage_pressure_axis', 'time_stamp', 'sequence_id', 'block_well_id',
       'rig_id', 'well_id', 'drilling_speed', 'rtk_status', 'd_depth',
       'd_time', 'speed', 'n/p', 'EI', 'EI 0-1', 'EI 1-2', 'EI 2-3', 'EI 3-4',
       'EI 4-5', 'EI 5-6', 'EI 6-7'],
      dtype='str')

In [66]:
df_clean = df.drop(columns=['id','electric_rotation', 'electric_pressure_axis', 'voltage_rotation',
       'voltage_pressure_axis', 'num_sattelites','moving_type', 'EI 0-1', 'EI 1-2', 'EI 2-3', 'EI 3-4',
       'EI 4-5', 'EI 5-6', 'EI 6-7','rod_change','sequence_id','rtk_status', 'rig_id', 'drilling_speed', 'time_stamp','block_well_id', 'processing_time'])

In [67]:
df_clean.dropna(inplace=True)

In [68]:
df_clean.head()

,time,lon,lat,height,depth,course,angle,rotation,pressure_air,pressure_axis,pressure_rotation,well_id,d_depth,d_time,speed,n/p,EI
1,2025-10-07 22:18:08,60.921372,53.208426,205.061214,4.6965,256,93.4,104.892,497,12781,13144,25512,0.1212,6.0,0.020200,0.008207,8.723352e+11
2,2025-10-07 22:18:13,60.921372,53.208427,205.078345,4.8783,359,93.0,101.430,501,18971,18936,25512,0.1818,5.0,0.036360,0.005347,1.002123e+12
3,2025-10-07 22:18:18,60.921373,53.208425,205.054763,5.0298,170,92.1,101.430,544,20153,18184,25512,0.1515,5.0,0.030300,0.005033,1.226741e+12
4,2025-10-07 22:18:23,60.921372,53.208425,205.065585,5.1813,218,93.0,102.714,559,20162,17445,25512,0.1515,5.0,0.030300,0.005094,1.192317e+12
5,2025-10-07 22:18:50,60.921372,53.208427,205.090648,5.3934,341,94.3,47.724,558,1233,10808,25512,0.2121,27.0,0.007856,0.038706,8.095960e+10

In [69]:
df_cluster = df_clean.copy()
df_cluster.drop(columns=['lon', 'lat', 'EI', 'height','course'], inplace=True)

In [70]:
df_cluster.to_csv("datasets/cluster.csv")

In [71]:
df_cluster.info()

<class 'pandas.DataFrame'>
Index: 165552 entries, 1 to 165965
Data columns (total 12 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   time               165552 non-null  str
 1   depth              165552 non-null  float64
 2   angle              165552 non-null  float64
 3   rotation           165552 non-null  float64
 4   pressure_air       165552 non-null  int64
 5   pressure_axis      165552 non-null  int64
 6   pressure_rotation  165552 non-null  int64
 7   well_id            165552 non-null  int64
 8   d_depth            165552 non-null  float64
 9   d_time             165552 non-null  float64
 10  speed              165552 non-null  float64
 11  n/p                165552 non-null  float64
dtypes: float64(7), int64(4), str(1)
memory usage: 16.4 MB